services:
  frontend:
    image: mightywalrus/frontend-dev
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: dev

    volumes:
      - ./client/:/code
      - /code/node_modules
    ports: 
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
      
  backend:
    image: mightywalrus/backend-dev
    build: 
      context: ./api
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./api/:/code
      - /code/node_modules
    ports: 
      - 5000:5000
    environment:
      - COOKIE_MAX_AGE=7200000
      - JWT_EXPIRES_IN=2h
      - PORT=5000
      - ALLOW_ORIGIN=http://localhost:3000
      - JWT_KEY=
      - COOKIE_SECRET=